language: erlang

env:
  global:
    - CASSANDRA_VERSION=2.1.5
  matrix:
    - LUA=lua5.1

branches:
  only:
    - master

before_install:
  - bash .travis/setup_kong.sh
  - bash .travis/setup_cassandra.sh

install:
  - sudo make install
  - sudo make dev
  - sudo sed -i.bak s@/usr/local/bin/luajit@/usr/bin/lua@g /usr/local/bin/busted

script:
  - "busted -o spec/busted-print.lua --coverage spec/"
  - "luacheck kong"

after_success: "luacov-coveralls -i kong"

after_script: "cat nginx_tmp/logs/error.log"
