language: erlang

env:
  global:
    - CASSANDRA_VERSION=2.1.5
  matrix:
    - LUA=lua5.1

branches:
  only:
    - master

before_install:
  - bash .travis/setup_kong.sh
  - bash .travis/setup_cassandra.sh

install:
  - sudo make install
  - sudo make dev
  - bash .travis/patch_busted.sh

script:
  - "busted spec/plugins/oauth2/"

after_script: "cat nginx_tmp/logs/error.log"
